<?xml version="1.0" encoding="utf-8"?><Database Name="deberes_4to" Class="MonolitoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=deberes_4to;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Capa_Datos.Properties.Settings" SettingsPropertyName="deberes_4toConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_juego_progreso" Member="tbl_juego_progreso">
    <Type Name="tbl_juego_progreso">
      <Column Name="progreso_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nivel_desbloqueado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mejor_puntuacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="monedas_totales" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ultima_partida" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_usuario_tbl_juego_progreso" Member="tbl_usuario" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_pro_fotos" Member="tbl_pro_fotos">
    <Type Name="tbl_pro_fotos">
      <Column Name="foto_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="foto_bit" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="foto_ruta" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="fecha_subida" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="foto_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="tbl_producto_tbl_pro_fotos" Member="tbl_producto" ThisKey="pro_id" OtherKey="pro_id" Type="tbl_producto" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_producto" Member="tbl_producto">
    <Type Name="tbl_producto">
      <Column Name="pro_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pro_cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pro_precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="pro_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="prov_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_producto_tbl_pro_fotos" Member="tbl_pro_fotos" ThisKey="pro_id" OtherKey="pro_id" Type="tbl_pro_fotos" />
      <Association Name="tbl_proveedor_tbl_producto" Member="tbl_proveedor" ThisKey="prov_id" OtherKey="prov_id" Type="tbl_proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_proveedor" Member="tbl_proveedor">
    <Type Name="tbl_proveedor">
      <Column Name="prov_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prov_nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prov_estado" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="tbl_proveedor_tbl_producto" Member="tbl_producto" ThisKey="prov_id" OtherKey="prov_id" Type="tbl_producto" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_proveedor_reasignacion_pendiente" Member="tbl_proveedor_reasignacion_pendiente">
    <Type Name="tbl_proveedor_reasignacion_pendiente">
      <Column Name="pendiente_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pro_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="proveedor_nombre" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_rol" Member="tbl_rol">
    <Type Name="tbl_rol">
      <Column Name="rol_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_rol" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="tbl_rol_tbl_usuario" Member="tbl_usuario" ThisKey="rol_id" OtherKey="rol_id" Type="tbl_usuario" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_usuario" Member="tbl_usuario">
    <Type Name="tbl_usuario">
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_nombres" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="usu_cedula" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="correo_electronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contraseña" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_nacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="edad" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="usu_nickname" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="numero_celular" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="codigo_otp" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="fecha_otp_generado" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="intentos_fallidos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rol_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_creacion" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="clave_temporal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tbl_usuario_tbl_juego_progreso" Member="tbl_juego_progreso" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_juego_progreso" />
      <Association Name="tbl_usuario_tbl_usuario_fotos" Member="tbl_usuario_fotos" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_usuario_fotos" />
      <Association Name="tbl_rol_tbl_usuario" Member="tbl_rol" ThisKey="rol_id" OtherKey="rol_id" Type="tbl_rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_usuario_fotos" Member="tbl_usuario_fotos">
    <Type Name="tbl_usuario_fotos">
      <Column Name="foto_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre_archivo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="content_type" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fecha_subida" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="es_principal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="foto_ruta" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="tbl_usuario_tbl_usuario_fotos" Member="tbl_usuario" ThisKey="usu_id" OtherKey="usu_id" Type="tbl_usuario" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_ResetearIntentosCaducados" Method="sp_ResetearIntentosCaducados">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_eliminar_proveedor_permanente" Method="sp_eliminar_proveedor_permanente">
    <Parameter Name="prov_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>