#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="deberes_4to")]
	public partial class MonolitoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_juego_progreso(tbl_juego_progreso instance);
    partial void Updatetbl_juego_progreso(tbl_juego_progreso instance);
    partial void Deletetbl_juego_progreso(tbl_juego_progreso instance);
    partial void Inserttbl_pro_fotos(tbl_pro_fotos instance);
    partial void Updatetbl_pro_fotos(tbl_pro_fotos instance);
    partial void Deletetbl_pro_fotos(tbl_pro_fotos instance);
    partial void Inserttbl_producto(tbl_producto instance);
    partial void Updatetbl_producto(tbl_producto instance);
    partial void Deletetbl_producto(tbl_producto instance);
    partial void Inserttbl_proveedor(tbl_proveedor instance);
    partial void Updatetbl_proveedor(tbl_proveedor instance);
    partial void Deletetbl_proveedor(tbl_proveedor instance);
    partial void Inserttbl_proveedor_reasignacion_pendiente(tbl_proveedor_reasignacion_pendiente instance);
    partial void Updatetbl_proveedor_reasignacion_pendiente(tbl_proveedor_reasignacion_pendiente instance);
    partial void Deletetbl_proveedor_reasignacion_pendiente(tbl_proveedor_reasignacion_pendiente instance);
    partial void Inserttbl_rol(tbl_rol instance);
    partial void Updatetbl_rol(tbl_rol instance);
    partial void Deletetbl_rol(tbl_rol instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    partial void Inserttbl_usuario_fotos(tbl_usuario_fotos instance);
    partial void Updatetbl_usuario_fotos(tbl_usuario_fotos instance);
    partial void Deletetbl_usuario_fotos(tbl_usuario_fotos instance);
    #endregion
		
		public MonolitoDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.deberes_4toConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonolitoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_juego_progreso> tbl_juego_progreso
		{
			get
			{
				return this.GetTable<tbl_juego_progreso>();
			}
		}
		
		public System.Data.Linq.Table<tbl_pro_fotos> tbl_pro_fotos
		{
			get
			{
				return this.GetTable<tbl_pro_fotos>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto> tbl_producto
		{
			get
			{
				return this.GetTable<tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor> tbl_proveedor
		{
			get
			{
				return this.GetTable<tbl_proveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbl_proveedor_reasignacion_pendiente> tbl_proveedor_reasignacion_pendiente
		{
			get
			{
				return this.GetTable<tbl_proveedor_reasignacion_pendiente>();
			}
		}
		
		public System.Data.Linq.Table<tbl_rol> tbl_rol
		{
			get
			{
				return this.GetTable<tbl_rol>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuario
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario_fotos> tbl_usuario_fotos
		{
			get
			{
				return this.GetTable<tbl_usuario_fotos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ResetearIntentosCaducados")]
		public int sp_ResetearIntentosCaducados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_eliminar_proveedor_permanente")]
		public int sp_eliminar_proveedor_permanente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prov_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prov_id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_juego_progreso")]
	public partial class tbl_juego_progreso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _progreso_id;
		
		private int _usu_id;
		
		private int _nivel_desbloqueado;
		
		private int _mejor_puntuacion;
		
		private int _monedas_totales;
		
		private System.Nullable<System.DateTime> _ultima_partida;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprogreso_idChanging(int value);
    partial void Onprogreso_idChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onnivel_desbloqueadoChanging(int value);
    partial void Onnivel_desbloqueadoChanged();
    partial void Onmejor_puntuacionChanging(int value);
    partial void Onmejor_puntuacionChanged();
    partial void Onmonedas_totalesChanging(int value);
    partial void Onmonedas_totalesChanged();
    partial void Onultima_partidaChanging(System.Nullable<System.DateTime> value);
    partial void Onultima_partidaChanged();
    #endregion
		
		public tbl_juego_progreso()
		{
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_progreso_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int progreso_id
		{
			get
			{
				return this._progreso_id;
			}
			set
			{
				if ((this._progreso_id != value))
				{
					this.Onprogreso_idChanging(value);
					this.SendPropertyChanging();
					this._progreso_id = value;
					this.SendPropertyChanged("progreso_id");
					this.Onprogreso_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel_desbloqueado", DbType="Int NOT NULL")]
		public int nivel_desbloqueado
		{
			get
			{
				return this._nivel_desbloqueado;
			}
			set
			{
				if ((this._nivel_desbloqueado != value))
				{
					this.Onnivel_desbloqueadoChanging(value);
					this.SendPropertyChanging();
					this._nivel_desbloqueado = value;
					this.SendPropertyChanged("nivel_desbloqueado");
					this.Onnivel_desbloqueadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mejor_puntuacion", DbType="Int NOT NULL")]
		public int mejor_puntuacion
		{
			get
			{
				return this._mejor_puntuacion;
			}
			set
			{
				if ((this._mejor_puntuacion != value))
				{
					this.Onmejor_puntuacionChanging(value);
					this.SendPropertyChanging();
					this._mejor_puntuacion = value;
					this.SendPropertyChanged("mejor_puntuacion");
					this.Onmejor_puntuacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monedas_totales", DbType="Int NOT NULL")]
		public int monedas_totales
		{
			get
			{
				return this._monedas_totales;
			}
			set
			{
				if ((this._monedas_totales != value))
				{
					this.Onmonedas_totalesChanging(value);
					this.SendPropertyChanging();
					this._monedas_totales = value;
					this.SendPropertyChanged("monedas_totales");
					this.Onmonedas_totalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ultima_partida", DbType="DateTime")]
		public System.Nullable<System.DateTime> ultima_partida
		{
			get
			{
				return this._ultima_partida;
			}
			set
			{
				if ((this._ultima_partida != value))
				{
					this.Onultima_partidaChanging(value);
					this.SendPropertyChanging();
					this._ultima_partida = value;
					this.SendPropertyChanged("ultima_partida");
					this.Onultima_partidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_juego_progreso", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_juego_progreso.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_juego_progreso.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_pro_fotos")]
	public partial class tbl_pro_fotos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _foto_id;
		
		private int _pro_id;
		
		private System.Data.Linq.Binary _foto_bit;
		
		private string _foto_ruta;
		
		private System.DateTime _fecha_subida;
		
		private System.Nullable<char> _foto_estado;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfoto_idChanging(int value);
    partial void Onfoto_idChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onfoto_bitChanging(System.Data.Linq.Binary value);
    partial void Onfoto_bitChanged();
    partial void Onfoto_rutaChanging(string value);
    partial void Onfoto_rutaChanged();
    partial void Onfecha_subidaChanging(System.DateTime value);
    partial void Onfecha_subidaChanged();
    partial void Onfoto_estadoChanging(System.Nullable<char> value);
    partial void Onfoto_estadoChanged();
    #endregion
		
		public tbl_pro_fotos()
		{
			this._tbl_producto = default(EntityRef<tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int foto_id
		{
			get
			{
				return this._foto_id;
			}
			set
			{
				if ((this._foto_id != value))
				{
					this.Onfoto_idChanging(value);
					this.SendPropertyChanging();
					this._foto_id = value;
					this.SendPropertyChanged("foto_id");
					this.Onfoto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_bit", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto_bit
		{
			get
			{
				return this._foto_bit;
			}
			set
			{
				if ((this._foto_bit != value))
				{
					this.Onfoto_bitChanging(value);
					this.SendPropertyChanging();
					this._foto_bit = value;
					this.SendPropertyChanged("foto_bit");
					this.Onfoto_bitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_ruta", DbType="NVarChar(255)")]
		public string foto_ruta
		{
			get
			{
				return this._foto_ruta;
			}
			set
			{
				if ((this._foto_ruta != value))
				{
					this.Onfoto_rutaChanging(value);
					this.SendPropertyChanging();
					this._foto_ruta = value;
					this.SendPropertyChanged("foto_ruta");
					this.Onfoto_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_subida", DbType="DateTime2 NOT NULL")]
		public System.DateTime fecha_subida
		{
			get
			{
				return this._fecha_subida;
			}
			set
			{
				if ((this._fecha_subida != value))
				{
					this.Onfecha_subidaChanging(value);
					this.SendPropertyChanging();
					this._fecha_subida = value;
					this.SendPropertyChanged("fecha_subida");
					this.Onfecha_subidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_estado", DbType="Char(1)")]
		public System.Nullable<char> foto_estado
		{
			get
			{
				return this._foto_estado;
			}
			set
			{
				if ((this._foto_estado != value))
				{
					this.Onfoto_estadoChanging(value);
					this.SendPropertyChanging();
					this._foto_estado = value;
					this.SendPropertyChanged("foto_estado");
					this.Onfoto_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_pro_fotos", Storage="_tbl_producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_pro_fotos.Remove(this);
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_pro_fotos.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(int);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto")]
	public partial class tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<decimal> _pro_precio;
		
		private System.Nullable<char> _pro_estado;
		
		private System.Nullable<int> _prov_id;
		
		private EntitySet<tbl_pro_fotos> _tbl_pro_fotos;
		
		private EntityRef<tbl_proveedor> _tbl_proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precioChanging(System.Nullable<decimal> value);
    partial void Onpro_precioChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onprov_idChanging(System.Nullable<int> value);
    partial void Onprov_idChanged();
    #endregion
		
		public tbl_producto()
		{
			this._tbl_pro_fotos = new EntitySet<tbl_pro_fotos>(new Action<tbl_pro_fotos>(this.attach_tbl_pro_fotos), new Action<tbl_pro_fotos>(this.detach_tbl_pro_fotos));
			this._tbl_proveedor = default(EntityRef<tbl_proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(50)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", DbType="Int")]
		public System.Nullable<int> prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					if (this._tbl_proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_pro_fotos", Storage="_tbl_pro_fotos", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<tbl_pro_fotos> tbl_pro_fotos
		{
			get
			{
				return this._tbl_pro_fotos;
			}
			set
			{
				this._tbl_pro_fotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_proveedor", ThisKey="prov_id", OtherKey="prov_id", IsForeignKey=true)]
		public tbl_proveedor tbl_proveedor
		{
			get
			{
				return this._tbl_proveedor.Entity;
			}
			set
			{
				tbl_proveedor previousValue = this._tbl_proveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_proveedor.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_proveedor.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._prov_id = value.prov_id;
					}
					else
					{
						this._prov_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_pro_fotos(tbl_pro_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = this;
		}
		
		private void detach_tbl_pro_fotos(tbl_pro_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor")]
	public partial class tbl_proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    #endregion
		
		public tbl_proveedor()
		{
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(50)")]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_proveedor_tbl_producto", Storage="_tbl_producto", ThisKey="prov_id", OtherKey="prov_id")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_proveedor_reasignacion_pendiente")]
	public partial class tbl_proveedor_reasignacion_pendiente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pendiente_id;
		
		private int _pro_id;
		
		private string _proveedor_nombre;
		
		private System.DateTime _fecha_registro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpendiente_idChanging(int value);
    partial void Onpendiente_idChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onproveedor_nombreChanging(string value);
    partial void Onproveedor_nombreChanged();
    partial void Onfecha_registroChanging(System.DateTime value);
    partial void Onfecha_registroChanged();
    #endregion
		
		public tbl_proveedor_reasignacion_pendiente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pendiente_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pendiente_id
		{
			get
			{
				return this._pendiente_id;
			}
			set
			{
				if ((this._pendiente_id != value))
				{
					this.Onpendiente_idChanging(value);
					this.SendPropertyChanging();
					this._pendiente_id = value;
					this.SendPropertyChanged("pendiente_id");
					this.Onpendiente_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proveedor_nombre", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string proveedor_nombre
		{
			get
			{
				return this._proveedor_nombre;
			}
			set
			{
				if ((this._proveedor_nombre != value))
				{
					this.Onproveedor_nombreChanging(value);
					this.SendPropertyChanging();
					this._proveedor_nombre = value;
					this.SendPropertyChanged("proveedor_nombre");
					this.Onproveedor_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime2 NOT NULL")]
		public System.DateTime fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_rol")]
	public partial class tbl_rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rol_id;
		
		private string _nombre_rol;
		
		private string _descripcion;
		
		private EntitySet<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onnombre_rolChanging(string value);
    partial void Onnombre_rolChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tbl_rol()
		{
			this._tbl_usuario = new EntitySet<tbl_usuario>(new Action<tbl_usuario>(this.attach_tbl_usuario), new Action<tbl_usuario>(this.detach_tbl_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_rol", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_rol
		{
			get
			{
				return this._nombre_rol;
			}
			set
			{
				if ((this._nombre_rol != value))
				{
					this.Onnombre_rolChanging(value);
					this.SendPropertyChanging();
					this._nombre_rol = value;
					this.SendPropertyChanged("nombre_rol");
					this.Onnombre_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_usuario", Storage="_tbl_usuario", ThisKey="rol_id", OtherKey="rol_id")]
		public EntitySet<tbl_usuario> tbl_usuario
		{
			get
			{
				return this._tbl_usuario;
			}
			set
			{
				this._tbl_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = this;
		}
		
		private void detach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_nombres;
		
		private string _usu_cedula;
		
		private string _correo_electronico;
		
		private string _contraseña;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private System.Nullable<int> _edad;
		
		private string _usu_nickname;
		
		private string _numero_celular;
		
		private string _codigo_otp;
		
		private System.Nullable<System.DateTime> _fecha_otp_generado;
		
		private int _intentos_fallidos;
		
		private int _rol_id;
		
		private System.DateTime _fecha_creacion;
		
		private bool _clave_temporal;
		
		private EntitySet<tbl_juego_progreso> _tbl_juego_progreso;
		
		private EntitySet<tbl_usuario_fotos> _tbl_usuario_fotos;
		
		private EntityRef<tbl_rol> _tbl_rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Oncorreo_electronicoChanging(string value);
    partial void Oncorreo_electronicoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void OnedadChanging(System.Nullable<int> value);
    partial void OnedadChanged();
    partial void Onusu_nicknameChanging(string value);
    partial void Onusu_nicknameChanged();
    partial void Onnumero_celularChanging(string value);
    partial void Onnumero_celularChanged();
    partial void Oncodigo_otpChanging(string value);
    partial void Oncodigo_otpChanged();
    partial void Onfecha_otp_generadoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_otp_generadoChanged();
    partial void Onintentos_fallidosChanging(int value);
    partial void Onintentos_fallidosChanged();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onfecha_creacionChanging(System.DateTime value);
    partial void Onfecha_creacionChanged();
    partial void Onclave_temporalChanging(bool value);
    partial void Onclave_temporalChanged();
    #endregion
		
		public tbl_usuario()
		{
			this._tbl_juego_progreso = new EntitySet<tbl_juego_progreso>(new Action<tbl_juego_progreso>(this.attach_tbl_juego_progreso), new Action<tbl_juego_progreso>(this.detach_tbl_juego_progreso));
			this._tbl_usuario_fotos = new EntitySet<tbl_usuario_fotos>(new Action<tbl_usuario_fotos>(this.attach_tbl_usuario_fotos), new Action<tbl_usuario_fotos>(this.detach_tbl_usuario_fotos));
			this._tbl_rol = default(EntityRef<tbl_rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(20)")]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this.Oncorreo_electronicoChanging(value);
					this.SendPropertyChanging();
					this._correo_electronico = value;
					this.SendPropertyChanged("correo_electronico");
					this.Oncorreo_electronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nickname", DbType="NVarChar(100)")]
		public string usu_nickname
		{
			get
			{
				return this._usu_nickname;
			}
			set
			{
				if ((this._usu_nickname != value))
				{
					this.Onusu_nicknameChanging(value);
					this.SendPropertyChanging();
					this._usu_nickname = value;
					this.SendPropertyChanged("usu_nickname");
					this.Onusu_nicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_celular", DbType="NVarChar(20)")]
		public string numero_celular
		{
			get
			{
				return this._numero_celular;
			}
			set
			{
				if ((this._numero_celular != value))
				{
					this.Onnumero_celularChanging(value);
					this.SendPropertyChanging();
					this._numero_celular = value;
					this.SendPropertyChanged("numero_celular");
					this.Onnumero_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_otp", DbType="NVarChar(60)")]
		public string codigo_otp
		{
			get
			{
				return this._codigo_otp;
			}
			set
			{
				if ((this._codigo_otp != value))
				{
					this.Oncodigo_otpChanging(value);
					this.SendPropertyChanging();
					this._codigo_otp = value;
					this.SendPropertyChanged("codigo_otp");
					this.Oncodigo_otpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_otp_generado", DbType="DateTime2")]
		public System.Nullable<System.DateTime> fecha_otp_generado
		{
			get
			{
				return this._fecha_otp_generado;
			}
			set
			{
				if ((this._fecha_otp_generado != value))
				{
					this.Onfecha_otp_generadoChanging(value);
					this.SendPropertyChanging();
					this._fecha_otp_generado = value;
					this.SendPropertyChanged("fecha_otp_generado");
					this.Onfecha_otp_generadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intentos_fallidos", DbType="Int NOT NULL")]
		public int intentos_fallidos
		{
			get
			{
				return this._intentos_fallidos;
			}
			set
			{
				if ((this._intentos_fallidos != value))
				{
					this.Onintentos_fallidosChanging(value);
					this.SendPropertyChanging();
					this._intentos_fallidos = value;
					this.SendPropertyChanged("intentos_fallidos");
					this.Onintentos_fallidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", DbType="Int NOT NULL")]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					if (this._tbl_rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime2 NOT NULL")]
		public System.DateTime fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this.Onfecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_creacion = value;
					this.SendPropertyChanged("fecha_creacion");
					this.Onfecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave_temporal", DbType="Bit NOT NULL")]
		public bool clave_temporal
		{
			get
			{
				return this._clave_temporal;
			}
			set
			{
				if ((this._clave_temporal != value))
				{
					this.Onclave_temporalChanging(value);
					this.SendPropertyChanging();
					this._clave_temporal = value;
					this.SendPropertyChanged("clave_temporal");
					this.Onclave_temporalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_juego_progreso", Storage="_tbl_juego_progreso", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_juego_progreso> tbl_juego_progreso
		{
			get
			{
				return this._tbl_juego_progreso;
			}
			set
			{
				this._tbl_juego_progreso.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_fotos", Storage="_tbl_usuario_fotos", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<tbl_usuario_fotos> tbl_usuario_fotos
		{
			get
			{
				return this._tbl_usuario_fotos;
			}
			set
			{
				this._tbl_usuario_fotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_usuario", Storage="_tbl_rol", ThisKey="rol_id", OtherKey="rol_id", IsForeignKey=true)]
		public tbl_rol tbl_rol
		{
			get
			{
				return this._tbl_rol.Entity;
			}
			set
			{
				tbl_rol previousValue = this._tbl_rol.Entity;
				if (((previousValue != value) 
							|| (this._tbl_rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_rol.Entity = null;
						previousValue.tbl_usuario.Remove(this);
					}
					this._tbl_rol.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario.Add(this);
						this._rol_id = value.rol_id;
					}
					else
					{
						this._rol_id = default(int);
					}
					this.SendPropertyChanged("tbl_rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_juego_progreso(tbl_juego_progreso entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_juego_progreso(tbl_juego_progreso entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
		
		private void attach_tbl_usuario_fotos(tbl_usuario_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = this;
		}
		
		private void detach_tbl_usuario_fotos(tbl_usuario_fotos entity)
		{
			this.SendPropertyChanging();
			entity.tbl_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario_fotos")]
	public partial class tbl_usuario_fotos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _foto_id;
		
		private int _usu_id;
		
		private string _nombre_archivo;
		
		private string _content_type;
		
		private System.Data.Linq.Binary _foto;
		
		private System.DateTime _fecha_subida;
		
		private bool _es_principal;
		
		private string _foto_ruta;
		
		private EntityRef<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfoto_idChanging(int value);
    partial void Onfoto_idChanged();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onnombre_archivoChanging(string value);
    partial void Onnombre_archivoChanged();
    partial void Oncontent_typeChanging(string value);
    partial void Oncontent_typeChanged();
    partial void OnfotoChanging(System.Data.Linq.Binary value);
    partial void OnfotoChanged();
    partial void Onfecha_subidaChanging(System.DateTime value);
    partial void Onfecha_subidaChanged();
    partial void Ones_principalChanging(bool value);
    partial void Ones_principalChanged();
    partial void Onfoto_rutaChanging(string value);
    partial void Onfoto_rutaChanged();
    #endregion
		
		public tbl_usuario_fotos()
		{
			this._tbl_usuario = default(EntityRef<tbl_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int foto_id
		{
			get
			{
				return this._foto_id;
			}
			set
			{
				if ((this._foto_id != value))
				{
					this.Onfoto_idChanging(value);
					this.SendPropertyChanging();
					this._foto_id = value;
					this.SendPropertyChanged("foto_id");
					this.Onfoto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int NOT NULL")]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if (this._tbl_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_archivo", DbType="NVarChar(255)")]
		public string nombre_archivo
		{
			get
			{
				return this._nombre_archivo;
			}
			set
			{
				if ((this._nombre_archivo != value))
				{
					this.Onnombre_archivoChanging(value);
					this.SendPropertyChanging();
					this._nombre_archivo = value;
					this.SendPropertyChanged("nombre_archivo");
					this.Onnombre_archivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_type", DbType="NVarChar(100)")]
		public string content_type
		{
			get
			{
				return this._content_type;
			}
			set
			{
				if ((this._content_type != value))
				{
					this.Oncontent_typeChanging(value);
					this.SendPropertyChanging();
					this._content_type = value;
					this.SendPropertyChanged("content_type");
					this.Oncontent_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_subida", DbType="DateTime2 NOT NULL")]
		public System.DateTime fecha_subida
		{
			get
			{
				return this._fecha_subida;
			}
			set
			{
				if ((this._fecha_subida != value))
				{
					this.Onfecha_subidaChanging(value);
					this.SendPropertyChanging();
					this._fecha_subida = value;
					this.SendPropertyChanged("fecha_subida");
					this.Onfecha_subidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_es_principal", DbType="Bit NOT NULL")]
		public bool es_principal
		{
			get
			{
				return this._es_principal;
			}
			set
			{
				if ((this._es_principal != value))
				{
					this.Ones_principalChanging(value);
					this.SendPropertyChanging();
					this._es_principal = value;
					this.SendPropertyChanged("es_principal");
					this.Ones_principalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_ruta", DbType="NVarChar(255)")]
		public string foto_ruta
		{
			get
			{
				return this._foto_ruta;
			}
			set
			{
				if ((this._foto_ruta != value))
				{
					this.Onfoto_rutaChanging(value);
					this.SendPropertyChanging();
					this._foto_ruta = value;
					this.SendPropertyChanged("foto_ruta");
					this.Onfoto_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_usuario_tbl_usuario_fotos", Storage="_tbl_usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_usuario tbl_usuario
		{
			get
			{
				return this._tbl_usuario.Entity;
			}
			set
			{
				tbl_usuario previousValue = this._tbl_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_usuario.Entity = null;
						previousValue.tbl_usuario_fotos.Remove(this);
					}
					this._tbl_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario_fotos.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(int);
					}
					this.SendPropertyChanged("tbl_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
