//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JORDYPRADO\\SQLEXPRESS01;Initial Catalog=deberes_4to;Integrated Securi" +
            "ty=True;Encrypt=True;TrustServerCertificate=True;")]
        public string deberes_4toConnectionString {
            get {
                return ((string)(this["deberes_4toConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JORDYPRADO\\SQLEXPRESS01;Initial Catalog=deberes_4to;Integrated Securi" +
            "ty=True;Encrypt=True;TrustServerCertificate=True")]
        public string deberes_4toConnectionString2 {
            get {
                return ((string)(this["deberes_4toConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JORDYPRADO\\SQLEXPRESS01;Initial Catalog=deberes_4to;Integrated Securi" +
            "ty=True;Encrypt=True;TrustServerCertificate=True")]
        public string deberes_4toConnectionString1 {
            get {
                return ((string)(this["deberes_4toConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JORDYPRADO\\SQLEXPRESS01;Initial Catalog=deberes_4to;Integrated Securi" +
            "ty=True;Encrypt=True;TrustServerCertificate=True")]
        public string deberes_4toConnectionString3 {
            get {
                return ((string)(this["deberes_4toConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=deberes_4to;Integrated Security=True;Encrypt=True;T" +
            "rustServerCertificate=True")]
        public string deberes_4toConnectionString4 {
            get {
                return ((string)(this["deberes_4toConnectionString4"]));
            }
        }
    }
}
